---
fixtures:
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    node_manager: 'https://github.com/WhatsARanjit/puppet-node_manager'
    apply_helpers: 'https://github.com/puppetlabs/puppetlabs-apply_helpers'
    bolt_shim: 'https://github.com/puppetlabs/puppetlabs-bolt_shim'
    debug: 'https://github.com/nwops/puppet-debug'
    format: 'https://github.com/voxpupuli/puppet-format'
  symlinks:
    "peadm": "#{source_dir}"
    out: "#{source_dir}/.bundle/gems/bolt-1.49.0/bolt-modules/out"
    ctrl: "#{source_dir}/.bundle/gems/bolt-1.49.0/bolt-modules/ctrl"
    file: "#{source_dir}/.bundle/gems/bolt-1.49.0/bolt-modules/file"
    system: "#{source_dir}/.bundle/gems/bolt-1.49.0/bolt-modules/system"
    boltlib: "#{source_dir}/.bundle/gems/bolt-1.49.0/bolt-modules/boltlib"
