---
Gemfile:
  required:
    ':development':
      - gem: 'puppet-debugger'
        version: '>= 0.18.0'
      - gem: 'bolt'
        version: '>= 2.42.0'
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
Rakefile:
  changelog_since_tag: '2.1.0'
  extras:
    - 'PuppetSyntax.exclude_paths = ["plans/**/*.pp", "vendor/**/*"]'
spec/spec_helper.rb:
    mock_with: ':rspec'
.gitignore:
  paths:
    - '.rerun.json'
    - '*.tar.gz'
    - '.modules/'
    - '.plan_cache.json'
    - '.resource_types/'
    - 'bolt-debug.log'
    - '!spec/fixtures/modules' # Have to reset this one to correctly not ignore peadm_spec
    - 'spec/fixtures/modules/*'
    - '!spec/fixtures/modules/peadm_spec'
