---
Gemfile:
  required:
    ':development':
      - gem: 'bolt'
        version: '>= 3.10.0'
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        version: '1.15.2' # Locked due to 1.16 no longer working for ruby lower than 3
      - gem: 'octokit'
        version: '4.21.0' # Locked due to https://github.com/octokit/octokit.rb/issues/1391
Rakefile:
  changelog_since_tag: '2.5.0'
  default_disabled_lint_checks: ['strict_indent','manifest_whitespace_missing_newline_end_of_file']
  extras:
    - 'PuppetSyntax.exclude_paths = ["plans/**/*.pp", "spec/acceptance/**/plans/**/*.pp", "vendor/**/*"]'
spec/spec_helper.rb:
    mock_with: ':rspec'
.gitignore:
  paths:
    - '.rerun.json'
    - '*.tar.gz'
    - '.modules/'
    - '.plan_cache.json'
    - '.resource_types/'
    - 'bolt-debug.log'
    - 'spec/docker/**/*.tar.gz'
    - 'spec/docker/**/*.asc'
    - 'spec/docker/**/files/puppet-enterprise*'
    - 'spec/docker/.task_cache.json'
.github/workflows/auto_release.yml:
  unmanaged: true 
.github/workflows/release.yml:
  unmanaged: true
