---
Gemfile:
  ':development':
     required:
       - gem: 'puppet-debugger'
         version: '>= 0.18.0'
Rakefile:
  extras:
    - 'PuppetSyntax.exclude_paths = ["plans/**/*.pp", "vendor/**/*"]'
.gitignore:
  paths:
    - '.rerun.json'
    - '*.tar.gz'
    
