---
Gemfile:
  required:
    ':development':
      - gem: 'puppet-debugger'
        version: '>= 0.18.0'
      - gem: 'bolt'
        version: '>= 3.10.0'
  optional:
    ':development':
      - gem: 'github_changelog_generator'
Rakefile:
  changelog_since_tag: '2.5.0'
  extras:
    - 'PuppetSyntax.exclude_paths = ["spec/acceptance/**/plans/**/*.pp", "vendor/**/*"]'
spec/spec_helper.rb:
    mock_with: ':rspec'
.gitignore:
  paths:
    - '.rerun.json'
    - '*.tar.gz'
    - '.modules/'
    - '.plan_cache.json'
    - '.resource_types/'
    - 'bolt-debug.log'
    - '!spec/fixtures/modules' # Have to reset this one to correctly not ignore peadm_spec
    - 'spec/fixtures/modules/*'
    - '!spec/fixtures/modules/peadm_spec'
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
