---
name: "On-demand smoke test"

on: [workflow_dispatch]

jobs:
  acceptance:
    name: "${{matrix.platform.label}}, ${{matrix.pe-version}}"
    runs-on: ubuntu-20.04
    env:
      BUILDEVENT_FILE: '../buildevents.txt'
    strategy:
      fail-fast: false
      matrix:
        platform:
          - label: 'RedHat Enterprise Linux 7'
            image: rhel-7
        pe-version:
          - '2019.8.5'

    steps:
    - name: 'Checkout Source'
      uses: actions/checkout@v2

    - name: 'Activate Ruby 2.7'
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.7"
        bundler-cache: true

    - name: 'Provision test VMs'
      run: |
        bundle exec rake spec_prep
        bundle exec bolt --modulepath spec/fixtures/modules plan run peadm_spec::provision_test_cluster image=${{matrix.platform.image}}
        echo ::group::=== REQUEST ===
        cat request.json || true; echo
        echo ::endgroup::
        echo ::group::=== INVENTORY ===
        sed -e 's/password: .*/password: "[redacted]"/' < inventory.yaml || true
        echo ::endgroup::

    - name: 'Remove test environment'
      if: ${{ always() }}
      continue-on-error: true
      run: |
        if [[ -f inventory.yaml || -f spec/fixtures/litmus_inventory.yaml ]]; then
          bundle exec rake 'litmus:tear_down'
          echo ::group::=== REQUEST ===
          cat request.json || true; echo
          echo ::endgroup::
        fi
